name: Figma EasyV Charts Components

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Create .env file
        env:
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
          DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        run: |
          touch .env
          echo DINGTALK_SECRET="$DINGTALK_SECRET">> .env
          echo DINGTALK_WEBHOOK_URL="$DINGTALK_WEBHOOK_URL" >> .env
      - name: Send Dingtalk Message
        run: npm run charts
