name: Figma EasyV Charts Components

on:
  schedule:
    - cron: '30 3,4,11,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Send Dingtalk Message
        run: npm run charts
